LibraryApp/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryApp.Models;
using LibraryApp.Models.ViewModels;

namespace LibraryApp.Controllers
{
    public class LibraryController : Controller
    {
        private LibraryDBContext context;
        public int PageSize = 3;

        public LibraryController(LibraryDBContext cnt)
        {
            context = cnt;
        }

        public IActionResult Index()
        {
            object connection = context.Database.ProviderName;

            return View(connection);

        }

        public IActionResult List(string genre = null, int page = 1)
        {
            BookList bookList = new BookList
            {
                Books = context.Books
                    .Where(g => genre == null || g.Genre.Name == genre)
                   .OrderBy(p => p.ID)
                   .Skip((page - 1) * PageSize)
                   .Take(PageSize),
                PagingInfo =  new PagingInfo{
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = genre == null ? context.Books.Count() : context.Books.Where(e => e.Genre.Name == genre).Count(),
                    CurrentGenre = genre
                },
            };

            return View("List", bookList);
            //if (bookList.Books.Count() != 0)

            //else return NotFound("Объекты не найдены");
        }

        //public IActionResult ListWithPageSize(int page = 1)
        //{
        //    return View("List", context.Books.OrderBy(p => p.ID).Skip((page - 1) * PageSize).Take(PageSize));
        //}

        

    }
}

LibraryApp/Controllers/ManagementController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using LibraryApp.Models;

namespace LibraryApp.Controllers
{
    public class ManagementController : Controller
    {
        private LibraryDBContext DBContext;

        public ManagementController (LibraryDBContext context)
        {
            DBContext = context;
        }

        public IActionResult Index()
        {
            return View(DBContext.Books);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Genres = DBContext.Genres;
            return View("Edit", new Book());
        }

        [HttpGet]
        public IActionResult Edit(int BookID)
        {
            ViewBag.Genres = DBContext.Genres;
            return View(DBContext.Books.FirstOrDefault(b => b.ID == BookID));
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            book.Genre = DBContext.Genres.FirstOrDefault(g => g.ID == book.GenreID);

            if(ModelState.IsValid)
            {
                if (book.ID != 0) DBContext.Books.Update(book);
                else if (book.ID == 0) DBContext.Books.Add(book);
                DBContext.SaveChanges();
                TempData["message"] = $"Книга {book.Name} была сохранена";
                return RedirectToAction("Index");
            }
            return View(book);
        }

        public IActionResult Delete(int BookID)
        {
            Book book = DBContext.Books.FirstOrDefault(b => b.ID == BookID);
            if(book != null)
            {
                DBContext.Books.Remove(book);
                DBContext.SaveChanges();
                TempData["message"] = $"Книга {book.Name} был(а) удален(а)";
            }
            return RedirectToAction("Index");
        }
    }
}

LibraryApp/Views/Library/AddBook.cshtml
@model LibraryApp.Models.Book
 
@{
    ViewData["Title"] = "AddProduct";
}

<h1>AddProduct</h1>

<form asp-action="AddBook" asp-controller="Library">
    <table>
        <tr>
            <td><label asp-for="Name" class="controll-label">Имя</label></td>
            <td><input type="text" asp-for="Name" class="form-control" /></td>
        </tr>
        <tr>
            <td><label asp-for="Description" class="controll-label">Описание</label></td>
            <td><input type="text" asp-for="Description" class="form-control" /></td>
        </tr>
        <tr>
            <td><label asp-for="Price" class="controll-label">Цена</label></td>
            <td><input type="text" asp-for="Price" class="form-control" /></td>
        </tr>
        <tr>
            <td><label asp-for="Genre" class="controll-label">Категория</label></td>
            <td> <input type="text" asp-for="Genre" class="form-control" /></td>
        </tr>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

LibraryApp/Views/Library/Index.cshtml
@{
    ViewData["Title"] = "Index";

}

<h1>Привет, мир!</h1>

<p><a asp-action="List" asp-controller="Library">Перейти к товарам</a></p>
<p><a asp-action="Index" asp-controller="Management">Перейти в управление</a></p>

<p>DB - @Model</p>

LibraryApp/Views/Library/List.cshtml
@model LibraryApp.Models.ViewModels.BookList

@foreach (var p in Model.Books)
{
    @*<div class="well">
        <h3>
            <strong>@p.Name</strong>
            <span class="pull-right label label-primary">
                @p.Price.ToString("c")
            </span>>
        </h3>
        <span class="lead"> @p.Description</span>
        <a asp-action="Delete" asp-controller="Library" asp-route-id="@p.ID">Удалить</a>
    </div>*@
    @*@Html.Partial("LibrarySummary", p)*@
    <partial name="LibrarySummary" model="p"/>
}
<div page-model="@Model.PagingInfo" page-action="List" 
        page-classes-enabled="true" 
        page-class="btn" 
        page-class-normal="btn-default" 
        page-class-selected="btn-primary"
        page-url-genre=@Model.PagingInfo.CurrentGenre
        class="btn-group pull-right">
</div>