LibraryApp/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using LibraryApp.Models;

namespace LibraryApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent (Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

LibraryApp/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryApp.Models;
using LibraryApp.Models.ViewModels;

namespace LibraryApp.Controllers
{
    public class LibraryController : Controller
    {
        private LibraryDBContext context;
        public int PageSize = 3;

        public LibraryController(LibraryDBContext cnt)
        {
            context = cnt;
        }

        public IActionResult Index()
        {
            object connection = context.Database.ProviderName;

            return View(connection);

        }

        public IActionResult List(string genre = null, int page = 1)
        {
            BookList bookList = new BookList
            {
                Books = context.Books
                    .Where(g => genre == null || g.Genre.Name == genre)
                   .OrderBy(p => p.ID)
                   .Skip((page - 1) * PageSize)
                   .Take(PageSize),
                PagingInfo =  new PagingInfo{
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = genre == null ? context.Books.Count() : context.Books.Where(e => e.Genre.Name == genre).Count(),
                    CurrentGenre = genre
                },
            };

            return View("List", bookList);
            //if (bookList.Books.Count() != 0)

            //else return NotFound("Объекты не найдены");
        }

        //public IActionResult ListWithPageSize(int page = 1)
        //{
        //    return View("List", context.Books.OrderBy(p => p.ID).Skip((page - 1) * PageSize).Take(PageSize));
        //}

        

    }
}

LibraryApp/Views/Shared/LibrarySummary.cshtml
@model Book

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.Price.ToString("c")
        </span>>
    </h3>
    <form id="@Model.ID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" name="bookid" value="@Model.ID"/>
        <input type="hidden" name="returnUrl" value=@ViewContext.HttpContext.Request.PathAndQuery()/>
        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right">Добавить в корзину</button>
        </span>
    </form>
    @*<a asp-action="Delete" asp-controller="Library" asp-route-id="@Model.ID">Удалить</a>*@
</div>

LibraryApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 m-1">
        <h4>@ViewBag.Title</h4>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

LibraryApp/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid"/>
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css"/>
    <title>Library</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="row">
            <a class="navbar-brand" asp-controller="Library" asp-action="Index">Library</a>
            <div class="col-lg-4 text-right ">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">@await Component.InvokeAsync("NavigationPanel")</div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>